#!/bin/sh

pip3 install tornado;
pip3 install motor;
mkdir -p /usr/local/lib/python3.5/site-packages/QmongoHelper  && cp -a  *.py  /usr/local/lib/python3.5/site-packages/QmongoHelper/
mkdir -p /usr/local/lib/python3.4/site-packages/QmongoHelper  && cp -a  *.py  /usr/local/lib/python3.4/site-packages/QmongoHelper/
